# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-05 17:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170105_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 17, 53, 22, 702521, tzinfo=utc)),
        ),
    ]
