# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 06:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170106_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 6, 6, 48, 27, 239853, tzinfo=utc)),
        ),
    ]
