# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 06:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170106_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_photo',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 6, 6, 50, 51, 308137, tzinfo=utc)),
        ),
    ]
