# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 08:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170106_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountholder',
            name='name',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 6, 8, 20, 26, 766409, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='AccountHolder',
        ),
    ]
