# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 13:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170106_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 6, 13, 55, 0, 14784, tzinfo=utc)),
        ),
    ]
