# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20170106_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 6, 14, 9, 6, 413567, tzinfo=utc)),
        ),
    ]
