# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-15 19:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20170116_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 15, 19, 12, 24, 369881, tzinfo=utc)),
        ),
    ]
